config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
#  get '/news', to: 'static_pages#news'
#  get '/about', to: 'static_pages#about'
  get '/company', to: 'static_pages#company'
  get '/recruit', to: 'static_pages#recruit'
  get '/work', to: 'static_pages#work'
  get '/privacy', to: 'static_pages#privacy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
  def privacy
  end

  def work
  end

  def company
  end

  def info
  end

  def recruit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title
      title = "柚希ジム" #ここにデフォルトの名前を入れてください。
      title = @page_title + " | " + title if @page_title
      title
    end
  end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer_content">
    <div class="footer_item">
      <ul><%= link_to "企業概要", company_path %></ul>
      <ul><%= link_to "活動内容", work_path %></ul>
      <ul><%= link_to "採用情報", recruit_path %></ul>
    </div>
    <div class="footer_item">
      <ul><%= link_to "プライバシーポリシー" , privacy_path %></ul>
      <ul><%= link_to "当サイトのご案内" , info_path %></ul>
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false"
      data-hashtags="柚希ジム">Tweet</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    </div>
  </div>
  <div class="footer_logo"></div>
  <p class="footer_copy">© Yzk-Gym LLC.</p>
</footer>

app/views/layouts/_header.html.erb
<header class="header-fixed"><!-- ハンバーガーメニューを開いたときにうまく表示されない -->
    <%= image_tag(image_path("Yzk-Gym-logo2.svg"), alt:"Yzk-Gym-logo", :class => "logo")%>
    <input id="nav-input" type="checkbox" class="nav-unshown">
    <label id="nav-open" for="nav-input"><span></span></label>
    <label class="nav-unshown" id="nav-close" for="nav-input"></label>
    <ul id="nav-content">
      <li class="items"><%= link_to "TOP", root_path ,:class => "item" %></li>
      <li class="items"><%= link_to "企業概要", company_path , :class => "item" %></li>
      <li class="items"><%= link_to "活動内容", work_path , :class => "item" %></li>
      <li class="items"><%= link_to "採用情報", recruit_path , :class => "item" %></li>
      <li class="items"><%= link_to "プライバシーポリシー", privacy_path , :class => "item" %></li>
      <li class="items"><%= link_to "当サイトのご案内", info_path , :class => "item" %></li>
      <div class="logo2"></div>
    </ul>
</header>

app/views/layouts/_news_topic.html.erb
<ul style="list-style:none;">
   <li class="box_link">
     <dl>
       <dt class="clearfix">
         <dd><%= image_tag(image_path("Yzk-Gym-logo1.png"), alt:"Yzk-Gym-logo", :class => "thumbnail", :size => "60x60") %></dd>
         <time class="date">xxxx/xx/xx</time>
         <dd class="comment">ここにコメントを入れる</dd>
       </dt>
     </dl>
   </li>
   <li class="box_link">
     <dl>
       <dt class="clearfix">
         <dd><%= image_tag(image_path("Yzk-Gym-logo1.png"), alt:"Yzk-Gym-logo", :class => "thumbnail", :size => "60x60") %></dd>
         <time class="date">xxxx/xx/xx</time>
         <dd class="comment">ここにコメントを入れる</dd>
       </dt>
     </dl>
   </li>
   <li class="box_link">
     <dl>
       <dt class="clearfix">
         <dd><%= image_tag(image_path("Yzk-Gym-logo1.png"), alt:"Yzk-Gym-logo", :class => "thumbnail", :size => "60x60") %></dd>
         <time class="date">xxxx/xx/xx</time>
         <dd class="comment">ここにコメントを入れる</dd>
       </dt>
     </dl>
   </li>
 </ul>

app/views/layouts/_rails_default.html.erb
<head>
  <meta charset="UTF-8">
  <title><%= page_title %></title>
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="柚希ジム｜楽しいを探しに行こう。">
  <meta name="twitter:description" content="合同会社柚希ジム コーポレートサイト">
  <meta name="twitter:image" content="<%= image_path("http://yzk-gym.com/assets/twitter_card_logo.jpg") %>" />
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= render 'layouts/shim' %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_tweetbtn.html.erb
<a href="https://twitter.com/share"
url=https%3A%2F%2Fdev.twitter.com%2Fweb%2Ftweet-button&
via=02320net&
hashtags="柚希未結生誕(仮)"
related=miu_u2>
<%= image_tag("twitter.svg", alt:"tweetbtn",:class=>"tweetbtn") %>
</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/rails_default' %>
  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
        <div class="debug_dump"><%= debug(params) if Rails.env.development? %></div>
      </div>
  </body>
</html>

app/views/static_pages/company.html.erb
<section class="company_title">
  <% @page_title = "企業概要" %>
  <h3>" Hard Enjoy "</h3>
  <p class="company_title_description">普通にやるんじゃつまらない。</br>
    どうせやるなら"Hard(本気)"にやろう。</br>
    本気で遊ぶから、本気の面白さになる。
  </p>
</section>
<div class="main_content_area">
  <section class="history_area">
    <div class="history_area2">
      <h1 class="history_title"><span id="title_txt">沿革</span></h1>
      <p class="history-date">2018/05/09</p>
      <p class="history-description">「合同会社 柚希ジム」設立。</p>
      <hr class="history-line">
      <p class="history-date">2017/09/24</p>
      <p class="history-description">柚希ジム エンジニアリング部 発足。</p>
      <hr class="history-line">
      <p class="history-date">2016/10/31</p>
      <p class="history-description">「柚希ジム」爆誕。</p>
      <%= image_tag(image_path("yzkgym_bakutan"), alt:"rana_matsui", :class => "history_image") %>
      <hr class="history-line">
      <p class="history-date">2016/10/29</p>
      <p class="history-description">柚希未結のヲタク、幻影ギャラクティカフリコピ選手権出場。</p>
      <hr class="history-line">
      <p class="history-date">2015/07/03</p>
      <p class="history-description">柚希未結 初ライブ。</p>
    </div>
  </section>
  <section class="office_area">
    <div class="office_area2">
      <h1 class="office_title"><span id="title_txt">オフィス紹介</span></h1>
      <p class="office_txt">東京・大阪を中心に、各地のライブハウス、スポッチャ、コワーキングスペースで活動しております。</p>
      <%= image_tag(image_path("office_varon"), alt:"varon", :class => "office_image") %>
      <%= image_tag(image_path("office_deepa"), alt:"deepa", :class => "office_image") %>
      <%= image_tag(image_path("office_cowork"), alt:"cowork", :class => "office_image") %>
      <%= image_tag(image_path("office_roundone"), alt:"roundone", :class => "office_image") %>
    </div>
  </section>
  <section class="company_info_area">
    <div class="company_info_area2">
      <h1 class="company_info_title"><span id="title_txt">会社情報</span></h1>
      <div class="ggmap"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.628981291859!2d139.6965670149577!3d35.66151168019891!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188ca9021ee8e1%3A0x52a368840fcb9299!2sWWW!5e0!3m2!1sja!2sjp!4v1525769030061" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe></div>
      <table class="company_info_table">
        <tr>
          <th>会社名</th>
          <td>合同会社 柚希ジム</br>(英文社名:Yzk-Gym LLC.)</td>
        </tr>
        <tr>
          <th>所在地</th>
          <td>〒150-0042</br>
            東京都渋谷区宇田川町13−17 ライズビル</br></br>
            5/20は上記の場所(渋谷WWW)にお越しください。</td>
        </tr>
        <tr>
          <th>設立</th>
          <td>2018年5月9日</td>
        </tr>
        <tr>
          <th>資本金</th>
          <td>10枚買っても1万円</td>
        </tr>
        <tr>
          <th>事業内容</th>
          <td>・柚希未結さんを応援する</br>
            ・Webサイト、サービスの企画・開発</br>
            ・スポッチャ</td>
        </tr>
      </table>
    </div>
  </section>
</div>

app/views/static_pages/expo.html.erb
<div class="expo">
  <h1 = class="title">当サイトのご説明</h1>
  <p class="txt">
    当サイトは柚希未結さんの名前をお借りしてはおりますが、あくまで柚希未結のヲタクによって設けられたものである為、
    柚希未結本人の活動及び意思とは一切関係ございません。
  </p>
  <p class="txt2">
    また、柚希未結さんの今後の活動、近況などについてのお問い合わせを頂いてもお答え致し兼ねますのでご了承ください。
  </p>
  <p class="byname">
    柚希ジム会員一同
  </p>
</div>

app/views/static_pages/home.html.erb
<div class="top" ><!--  とりあえず画像とか決まるまで代用 -->
  <h1 class="top_copy">Make</br>with</br>Buddy</h1>
  <% @page_title = "Make with Buddy" %>
  <%= image_tag(image_path("yzkgym_top"), alt:"top", :class => "top_image") %>
</div>
<section class="news_area" >
  <div class="news_area2">
    <h1 class="news_title">お知らせ</h1>
    <ul class="news_list">
      <li class="news_item">
        <p class="news_date">2018/05/13</p>
        <p class="news_subtitle">柚希未結生誕・引退ライブ参加のお知らせ</p>
        <p class="news_description">5/20(日)柚希未結生誕・引退ライブ<br/>「Fight with Buddy～最終決戦!!!!!～」<br/>@渋谷WWW<br/>
        op 13:30 st 14:00 end 21:00<br/><br/>
          柚希ジム一同で参加いたします。<br/><br/>
        チケットは下記サイトで購入できます。ぜひ一緒に楽しみましょう！<br/>
        <a href="http://sort.eplus.jp/sys/T1U14P0010163P0108P002247975P0050001P006001P0030001" target="_blank">eplusへ</a></p>
      </li>
      <hr class="news_border">
      <li class="news_item">
        <p class="news_date">2018/5/13</p>
        <p class="news_subtitle">弊社コーポレートサイトを開設いたしました</p>
        <p class="news_description">柚希ジム プログラミング研修の一環として、コーポレートサイトを開設いたしました。</p>
      </li>
      <hr class="news_border">
      <li class="news_item">
        <p class="news_date">2016/10/29</p>
        <p class="news_subtitle">幻影ギャラクティカフリコピ選手権出場</p>
        <p class="news_description">27時間HNG2016 内の『幻影ギャラクティカフリコピ選手権』に出場いたしました。<br/>
        優勝することは出来ませんでしたが、柚希ジムの結束を高めることが出来ました。<br/>
        応援ありがとうございました。</p>
      </li>
    </ul>
  </div>
</section>
<section class="about_area">
  <div class="about_area2">
    <h1 class="about_title"><span id="title_txt">企業概要</span></h1>
    <section class="home_company_title">
      <h3>" Hard Enjoy "</h3>
    </section>
    <p class="box_txt">柚希ジムの理念、沿革、所在地等をご紹介します。</p>
    <div class="session_btn"><%= link_to "詳しく見る", company_path, :class => "btn" %></div><!-- ボタンのデザイン -->
  </div>
</section>
<section class="work_area">
  <div class="work_area2">
    <h1 class="work_title">活動内容</h1>
    <%= image_tag(image_path("dance2"), alt:"dance", :class => "session_image") %>
    <p class="box_txt">
      本気で遊び、本気で楽しむ中で得た、多くの人たちと創ってきた"楽しい"をカタチにしたいという想いで日々活動しています。
    </p>
    <div class="session_btn">
        <%= link_to "詳しく見る", work_path, :class => "btn"%>
    </div>
  </div>
</section>
<section class="recruit_area">
  <div class="recruit_area2">
    <h1 class="recruit_title">採用情報</h1>
    <%= image_tag(image_path("macmen"), alt:"recruit", :class => "session_image") %>
    <p class="box_txt">
      私たちと一緒に"楽しい"をつくる意欲のある方をお待ちしております。
    </p>
    <div class="session_btn"><%= link_to "詳しく見る", recruit_path, :class => "btn" %></div>
  </div>
</section>

app/views/static_pages/info.html.erb
<div class="info">
  <h1 class="title">当サイトのご案内</h1>
  <% @page_title = "当サイトのご案内" %>
  <p class="txt">
    当サイトは柚希未結さんの名前をお借りしてはおりますが、あくまで柚希未結のヲタクによって設けられたものである為、
    柚希未結さん本人の活動及び意思とは一切関係ございません。
  </p>
  <p class="txt2">
    また、柚希未結さんの今後の活動、近況などについてのお問い合わせを頂いてもお答え致し兼ねますのでご了承ください。
  </p>
  <p class="byname">
    柚希ジム会員一同
  </p>
</div>

app/views/static_pages/privacy.html.erb
<div class="privacy">
  <% @page_title = "プライバシーポリシー" %>
  <h1 class="policy">プライバシーポリシー</h1>
  <h2 class="using">個人情報の取り扱いに関して</h2>
  <p class="txt">
      合同会社柚希ジム(以下、当ジム)は、個人情報保護法の遵守のため、ヲタクの皆様方をはじめ、
    当ジムに関係する方々の個人情報を保護することは不可欠の要素だと考えております。
    そのため、当ジムの個人情報保護方針(プライバシーポリシー)に基づき、以下の通り取り扱います。
  </p>
  <h3 class="title">1.個人情報の取得</h3>
  <p class="txt">
      製品サービスの向上のため、Twitter等のSNSにアップロードされた写真や動画などのヲタクの皆様の
    個人情報を利用させていただく場合がございます。
    また、当ジムでは来たる5/20柚希未結生誕・引退ライブに伴い、Twitterアカウント等の皆様の個人情報をお伺いする事がございます。
    なお、ご提供いただいた個人情報はこれらの目的以外には一切利用致しません。
  </p>

    <h3 class="title">2.個人情報の利用</h3>
    <p class="txt">
        当ジムが保有するお客様の個人情報を、お客様の同意なしに第三者に開示・提供することはありません。
      ただし、以下の場合は、お客様の同意なく個人情報を開示・提供することがあります。
    </p>
    <ul class="items">
      <li>法令に基づく場合。</li>
      <li>人の生命、身体又は財産の保護のために必要がある場合であって、お客様の同意を得ることが困難であるとき。</li>
      <li>公衆衛生の向上又は児童の健全な育成の推進のために特に必要がある場合であって、お客様の同意を得ることが困難であるとき。</li>
      <li>
        国の機関若しくは地方公共団体又はその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって、
        お客様の同意を得る
        ことにより当該事務の遂行に支障を及ぼすおそれがあるとき。
      </li>
      <li>どうしても面白そうなとき。</li>
    </ul>

    <h3 class="title">3.個人情報の提供</h3>
    <p class="txt">
        当ジムは、皆様方から得た個人情報を、本人の同意なく第三者に提供することはございません。
    </p>
  </div>

  <!--
  <h3>個人情報の預託</h3>

  <h3>個人情報の取得</h3>
-->

app/views/static_pages/recruit.html.erb
<body>
  <div class="title">
    <% @page_title = "採用情報" %>
    <%= image_tag(image_path("macmen"), alt:"recruit", :class => "title_image") %>
    <h1 class="content_title">採用情報<h1>
  </div>
  <section class="recruitment_area">
  <div class="recruitment_area2">
    <h1 class="recruitment_title"><span id="title_txt">募集要項</span></h1>
    <table class="recruitment_table">
        <tr>
          <th>応募資格</th>
          <td>ライブを楽しみたい方</td>
        </tr>
        <tr>
          <th>募集職種</th>
          <td>楽しいライブのヲタク</td>
        </tr>
        <tr>
          <th>勤務地</th>
          <td>・ライブハウス<br>
          ・コワーキングスペース<br>
          ・スタジオ など</td>
        </tr>
        <tr>
          <th>勤務時間</th>
          <td>働きたい時</td>
        </tr>
        <tr>
          <th>休日</th>
          <td>休みたい時</td>
        </tr>
    </table>
  </div>
</section>
<section class="policy_area">
  <div class="policy_area2">
    <h1 class="policy_title"><span id="title_txt">人材育成方針</span></h1>
    <p class="policy_txt"><strong>『推しメンと共に成長する』</strong><br/>
    を人材育成の方針としております。私たちの推しメンである柚希未結さんの成長と共に、自分自身もライブや研修を通して成長することで自律的な人材、
    多方面で活躍できる人材の育成に取り組んでいます。</p>
  </div>
</section>
<section class="trainings_area">
  <div class="trainings_area2">
    <h1 class="trainings_title"><span id="title_txt">研修</span></h1>
    <%= image_tag(image_path("dance1.jpg"), alt:"furikopi", :class => "session_image") %>
    <p class="trainings_subtitle">フリコピ研修</p>
    <p class="trainings_txt">日々のライブをより楽しむことができるように各自での練習に加え、スタジオや公園、ゲームセンターなどでフリコピの練習をします。<br/>
    研修実績：幻影ギャラクティカフリコピ選手権出場</p>
    <hr class="trainings_line">
    <%= image_tag(image_path("study3.jpg"), alt:"programming", :class => "session_image") %>
    <p class="trainings_subtitle">プログラミング研修<br/>
    <p class="trainings_txt">プログラミングの基礎からWebサイトを制作できるようになるまでを、チームでの開発を通して学びます。<br/>
    研修実績：本コーポレートサイトの制作</p>
  </div>
</section>

app/views/static_pages/work.html.erb
<session>
  <div class="work_top"><!-- ここら辺は周りと合わせる-->
    <% @page_title = "活動内容" %>
    <%= image_tag(image_path("dance2"), alt:"dance", :class=> "dance") %>
    <h1 class="content_title">活動内容</h1>
  </div>
</session>
<session class="item_box1">
  <div class="item_contena">
    <h1 class="box_title">幻影ギャラクティカフリコピ選手権</h1>
    <div class="video">
      <iframe width=auto height=auto
      src="https://www.youtube.com/embed/3rnlNEetQgQ?rel=0" frameborder="0"
      allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div>
    <p class="text">
      自主練習やスタジオ練習、合宿を通して、何かに本気になることの苦労や楽しさを思い出しました。
      部活動のような一夏の出来事を通して"どのように行動したいか"を考えるきっかけとなりました。</p>
  </div>
</session>
<session class="item_box2">
  <div class="item_contena">
    <h1 class="box_title">異文化交流</h1>
    <%= image_tag(image_path("Js"), alt:"Js", :class => "Js")  %>
    <p class="text">
      異なる文化に対しても、とにかくやってみるという気持ちを持って積極的にふれあい、
      自分たちの新たな"楽しい"を生み出し続けています。</p>
  </div>
</session>
<session class="item_box3">
  <div class="item_contena">
    <h1 class="box_title">プログラミング学習</h1>
    <%= image_tag(image_path("study2"), alt:"study", :class => "studying") %>
    <p class="text">
      与えられたものをただ楽しむだけでなく、たくさんの人たちに"面白い"、"楽しい"と感じてもらえるような
      モノ作りにも挑戦したいと考え、その一環としてプログラミングを学んでいます。
    </p>
  </div>
</session>